In [1]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
train_data = pd.read_csv('sign_mnist_train.csv')
test_data = pd.read_csv('sign_mnist_test.csv')

In [3]:
#784 pixels per image
train_data.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      3     107     118     127     134     139     143     146     150   
1      6     155     157     156     156     156     157     156     158   
2      2     187     188     188     187     187     186     187     188   
3      2     211     211     212     212     211     210     211     210   
4     13     164     167     170     172     176     179     180     184   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0     153  ...       207       207       207       207       206       206   
1     158  ...        69       149       128        87        94       163   
2     187  ...       202       201       200       199       198       199   
3     210  ...       235       234       233       231       230       226   
4     185  ...        92       105       105       108       133       163   

   pixel781  pixel782  pixel783  pixel784  
0       206       204       203       202  
1       175       103       135       149  
2       198       195       194       195  
3       225       222       229       163  
4       157       163       164       179  

[5 rows x 785 columns]

In [4]:
labels = np.array((train_data['label'].unique()))
print(f"Sorted labels: {np.sort(labels)}")
print(f"No. labels: {len(labels)}")

Sorted labels: [ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
No. labels: 24


In [5]:
train_data.loc[train_data['label'] > 8, 'label'] = train_data['label'] - 1

In [6]:
test_data.loc[train_data['label'] > 8, 'label'] = train_data['label'] - 1

In [7]:
labels = np.array((train_data['label'].unique()))
print(f"Sorted labels: {np.sort(labels)}")
print(f"No. labels: {len(labels)}")

Sorted labels: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
No. labels: 24


In [8]:
train_data.shape

(27455, 785)

In [9]:
#train/test split
X_train = np.array(train_data.drop(['label'], axis = 1, inplace=False))
y_train = np.array(train_data['label'])
X_test = np.array(test_data.drop(['label'], axis = 1, inplace=False))
y_test = np.array(test_data['label'])

In [10]:
print(X_train)
print(X_train.shape)

[[107 118 127 ... 204 203 202]
 [155 157 156 ... 103 135 149]
 [187 188 188 ... 195 194 195]
 ...
 [174 174 174 ... 202 200 200]
 [177 181 184 ...  64  87  93]
 [179 180 180 ... 205 209 215]]
(27455, 784)


In [49]:
#normalizing
X_train = X_train/255
X_train

array([[0.41960784, 0.4627451 , 0.49803922, ..., 0.8       , 0.79607843,
        0.79215686],
       [0.60784314, 0.61568627, 0.61176471, ..., 0.40392157, 0.52941176,
        0.58431373],
       [0.73333333, 0.7372549 , 0.7372549 , ..., 0.76470588, 0.76078431,
        0.76470588],
       ...,
       [0.68235294, 0.68235294, 0.68235294, ..., 0.79215686, 0.78431373,
        0.78431373],
       [0.69411765, 0.70980392, 0.72156863, ..., 0.25098039, 0.34117647,
        0.36470588],
       [0.70196078, 0.70588235, 0.70588235, ..., 0.80392157, 0.81960784,
        0.84313725]])

In [11]:
np.unique(y_train)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [62]:
import importlib
import mlp
importlib.reload(mlp)
model = mlp.MLP()

In [63]:
model.train(X_train.T, y_train, alpha = 0.1, iterations=10000)

Iteration:  0
[22 22 22 ... 22  1  1] [ 3  6  2 ... 17 16 22]
0.04017483154252413
Iteration:  10
[20 20 20 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.04206883991986888
Iteration:  20
[20 20 20 ... 20 20 20] [ 3  6  2 ... 17 16 22]
0.04308869058459297
Iteration:  30
[20 20 20 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.04265161172828264
Iteration:  40
[20 20 20 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.04192314696776543
Iteration:  50
[20 20 20 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.042250956109998176
Iteration:  60
[20 20 20 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.043416499726825715
Iteration:  70
[20 20 20 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.04753232562374795
Iteration:  80
[20 20 23 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.049462757239118554
Iteration:  90
[20 20 23 ... 20 23 20] [ 3  6  2 ... 17 16 22]
0.04702240029138591
Iteration:  100
[20 16 23 ... 20 23 16] [ 3  6  2 ... 17 16 22]
0.04753232562374795
Iteration:  110
[20 16 23 ... 20 23 16] [ 3  6  2 ... 17 16 22]
0.05062830085594609


In [ ]:
model.learning_curve()